### ISSUE TITLE
接入AppInit后发现修改代码直接运行编译不进去

### ISSUE THREAD

**Issue by wjianchen13** [Meituan-Dianping/AppInit#12]
接入了AppInit之后发现修改代码直接运行编译不进去，需要重新clean，rebuild才可以，或者退出IDE重新进入，请问这个是什么原因造成的?

**Comment by lianghuiyong** [comment]
我以为是，构建运行就会提示
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
再次构建运行就好了

**Comment by bingoogolapple** [comment]
试了下只在 Windows 上才会出现，暂时先用执行「gradlew --stop」命令来解决吧
