### ISSUE TITLE
重新编译失败，必须重启Android studio才能删除app模块下的build文件夹

### ISSUE THREAD

**Issue by guozhiqiang123** [Meituan-Dianping/AppInit#13]
# Issue/提问须知

在提交 issue 之前，我们应该先查询是否已经有相关的 issue 和[使用文档](https://github.com/Meituan-Dianping/AppInit/blob/master/docs/user-manual.md)。提交 issue 时，我们需要写明 issue 的原因，最好可以携带编译或运行过程的日志或者截图。issue 需要以下面的格式提出：

----

* 异常类型：app 运行时异常/编译异常

* 手机型号（如是编译异常，则可以不填）：如：Nexus 4

* 手机系统版本（如是编译异常，则可以不填）：如：Android 5.0

* AppInit 版本：如：1.0.3

* Gradle 版本：如：3.1.4

* 系统：如：windows 10

* 堆栈/日志或者截图：

第一次能run成功，但是第二次run的时候或者instant run的时候就报下面的异常：
Unable to delete file: ...\app\build\intermediates\transforms\TransformPluginLaunch\debug\0.jar

然后我直接去目录下 手动删除app模块下的build文件夹，提示我要删除的文件正在OpenJDK中打开，这个时候我只能先把Android studio关闭，然后再删除才能成功。
我怀疑是框架中往build下生成代码的时候，没有及时关闭流。因为我在没有使用这个框架的时候是没有这个问题的。

**Comment by bingoogolapple** [comment]
之前也有人遇到类似问题，但是 Mac 上一直复现不了

![image](https://user-images.githubusercontent.com/8949716/56078450-bdeb8400-5e1a-11e9-855b-28f57b3fddde.png)
我怀疑是 common-io 这个库 2.6 版本没有关闭流导致的
![image](https://user-images.githubusercontent.com/8949716/56078459-dbb8e900-5e1a-11e9-8823-351de0ecd082.png)
你那边方便注释掉 commons-io 的依赖或强制指定其版本号为 2.4 试试吗？

**Comment by bingoogolapple** [comment]
刚才发了一个 1.0.4 版本，试下是否还存在该问题

**Comment by guozhiqiang123** [comment]
换成1.0.4还是不行，
当我手动去上app模块下的build文件的时候就提示下面这个


java.io.IOException: Cannot delete 'C:\Users\***\Desktop\AndroidCore\app\build'
------------------

 





------------------ 原始邮件 ------------------
发件人: "王浩"<notifications@github.com>;
发送时间: 2019年4月13日(星期六) 晚上7:09
收件人: "Meituan-Dianping/AppInit"<AppInit@noreply.github.com>;
抄送: "郭志强"<774550196@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Meituan-Dianping/AppInit] 重新编译失败，必须重启Android studio才能删除app模块下的build文件夹 (#13)




刚才发了一个 1.0.4 版本，试下是否还存在该问题

**Comment by guozhiqiang123** [comment]
我刚把你这个整个项目拉下来跑了一下 ，但是运行不起来。报下面的错误：
Unexpected scopes found in folder 'C:\Users\\Desktop\AppInit\demo\app\build\intermediates\transforms\WMRouter\debug'. Required: PROJECT, EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

**Comment by guozhiqiang123** [comment]
如果方便的话，加个QQ：774550196，我把调试信息发你看看。

**Comment by guozhiqiang123** [comment]
![微信截图_20190413212849](https://user-images.githubusercontent.com/20378988/56080402-4fff8680-5e33-11e9-8cc4-553bf9b438be.png)
![微信截图_20190413212923](https://user-images.githubusercontent.com/20378988/56080406-57bf2b00-5e33-11e9-8bb0-cc74845e0efa.png)
这个是我去文件夹里面手动删删不掉的文件

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/56081732-15054f00-5e43-11e9-8c3f-48c7daf8088a.png)

TransformPluginLaunch 是哪个插件 AppInit 生成的文件在「app/build/intermediates/transforms/AppInit/debug/」下的

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/56081935-4bdc6480-5e45-11e9-8c9b-82706e4daa25.png)
截图看下挨着 transformClassesWithAppinitForDebug 这个 task 的前后 task

**Comment by guozhiqiang123** [comment]
![1555170626(1)](https://user-images.githubusercontent.com/20378988/56082077-f903ac80-5e46-11e9-8a05-0b639d36746a.jpg)
![微信截图_20190413235255](https://user-images.githubusercontent.com/20378988/56082101-48e27380-5e47-11e9-8d2d-fb8bebe710ad.png)

**Comment by bingoogolapple** [comment]
试了下只在 Windows 上才会出现，暂时先用执行「gradlew --stop」命令来解决吧
