### ISSUE TITLE
请问一定要用gradle4.4 嘛？

### ISSUE THREAD

**Issue by hyr0318** [Meituan-Dianping/AppInit#16]
* 异常类型：多渠道打包

* 手机型号（如是编译异常，则可以不填）：如：Nexus 5

* 手机系统版本（如是编译异常，则可以不填）：如：Android 5.0

* AppInit 版本：如：1.0.5

* Gradle 版本：如：4.4

* 系统：如：Mac

* 堆栈/日志或者截图：

----
现在项目使用packer 打对渠道包，但是升到4.4 之后渠道包不能成功，4.1 时候就可以。请问appinit 一定要将gradle 升到4.4 么

**Comment by bingoogolapple** [comment]
升级到 4.4 之前「com.android.tools.build:gradle」对应的版本是多少？
