### ISSUE TITLE
demo运行不了

### ISSUE THREAD

**Issue by xiaoxiangyeyuHeaven** [Meituan-Dianping/AppInit#17]
demo运行不了

**Comment by xiaoxiangyeyuHeaven** [comment]
模块《AppInit:module2》不存在
        《demo:app》[priority=3][dependencies=AppInit:module2, com.sankuai.erp.component:appinit-test-module1]=> 依赖的模块《AppInit:module2》不存在

**Comment by bingoogolapple** [comment]
未发布到 maven 仓库时模块坐标生成规则为「模块父目录名称:模块名称」

AppInit
----module2

如果修改了 AppInit 为其他名称，依赖的坐标名称也要修改一下
