### ISSUE TITLE
编译报错，如图

### ISSUE THREAD

**Issue by hyr0318** [Meituan-Dianping/AppInit#19]
* 异常类型：编译异常

* 手机型号（如是编译异常，则可以不填）：如：Nexus 5

* 手机系统版本（如是编译异常，则可以不填）：如：Android 10.0

* AppInit 版本：最新版本

* Gradle 版本：如：6.0

* 系统：如：Mac

* 堆栈/日志或者截图：
![1576491556812](https://user-images.githubusercontent.com/15108892/70899066-df97ad80-2030-11ea-9e0f-ec272aff4110.jpg)

**Comment by bingoogolapple** [comment]
这个不是 AppInit 里报的
